software-maestro-starting-blue/fourtooncookie-backend

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/MemberRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Role.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
---
* 구현 내용
member에 role 추가, repository 및 service 추가
=> [feat] member에 role 추가, repository 및 service 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/CharacterController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/controller/CharacterController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/Character.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/CharacterRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/ModelType.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/AddCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponses.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/exception/CharacterNoSuchElementException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/exception/ModelTypeNoSuchElementException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java
---
* 구현 내용
캐릭터 추가 api
---
* 구현 내용
캐릭터 수정 api
put이므로 수정하지 않는 부분도 전체 값을 모두 입력해야 함
* ### TSK-155
---
* 구현 내용
캐릭터 삭제 api
soft delete가 아니므로 db에서 완전 제거됨
* ### TSK-181
---
* 구현 내용
캐릭터 전체 조회 api
일단은 전체 조회로 구현했는데 ui 상 모델별로 보여준다면 전체 조회하고 ui 상에서 분류해서 보여주면 될 수도 있습니다.
근데 다른 방법도 있을법합니다.
=> [feat] 캐릭터 추가, 수정, 삭제, 전체 조회 api 구현

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java
---
* 구현 내용
- DiaryRepository 
`Page<Diary> findAllByMember(Member member, Pageable pageable)`  → `Page<Diary> findAllByMemberOrderByDiaryDateDesc(Member member, Pageable pageable)` 로 메서드명 변경
=> refactor: Diary Repository 리팩토링 및 테스트 코드 작성

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/llm/service/LLMService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/apply/service/VisionApplyMainService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/apply/service/VisionApplyManageService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/apply/service/VisionApplyService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/controller/VisionReplyController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/controller/VisionReplyEventListener.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/dto/VisionReplyEvent.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/dto/VisionReplyRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/service/VisionReplyService.java
---
* 구현 내용
백엔드에서 ai 로직을 활용하기 위한 llm과 vision 패키지를 구성하였습니다.
vision로직은 다음과 같이 구성되었습니다.
1. VisionApplyManageService에서 이미지를 생성하도록 VisionApplyService(어떤 구현체)에게 요청
2. VisionApplyService에서 Vision 생성을 요청
3. 해당 서비스에서 이미지를 생성 (DallE, Midjourney, SD)
4. 만약, 코드 상으로 직접 응답이 왔으면, 해당 코드에서 VisionReplyEvent를 발생시켜서 내용을 VisionReplyEventListener로 전달
만약, VisionApplyService가 아닌 Http 응답이 온다면, VisionReplyController에서 해당 내용을 받음
5. VisionReplyEventListener 혹은 VisionReplyController에서 요청이 온다면 VisionReplyService로 해당 내용을 전달하여서 그 후 이미지 S3 업로드 및 Diary 테이블 적용 진행
이 후 다른 백로그에서 각 구현체를 구현할 예정입니다.
=> [feat] 백엔드 AI 패키지 구조 구성

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/discord/service/DiscordService.java
---
* 구현 내용
Discord 봇을 관리하는 서비스 로직을 구현하였습니다.
=> [feat] Discord 서비스 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/CharacterController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/Character.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/CharacterRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/AddCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/service/CharacterServiceTest.java
---
- selectionThumbnailUrl 자료형 String 에서 URL 로 변경
- 필요 없는 calendarThumbnailUrl 필드 제거
- 모든 캐릭터를 가져오는 코드 변경 -> 모델 타입에 맞는 캐릭터 가져오기
- 테스트 코드 작성
- findAllByModelType: 특정 모델 타입의 모든 캐릭터를 가져온다.
=> refactor: Character 코드 리팩토링 및 테스트 코드 작성

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java
---
* 구현 내용
- Diary 필드 NotNull 추가
- Diary, DiaryService, DiaryRepsotiory 테스트 코드 추가
=> refactor & test : Diary, DiaryService, DiaryRepsotiory 테스트 코드 추가 

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/llm/service/OpenAIGpt4oLLMService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/llm/service/OpenAILLMService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/llm/service/OpenAIGpt4oLLMServiceTest.java
---
* 구현 내용
LLM Service의 구현체 중 하나인 OpenAIGpt4oLLMService 로직을 구현하였습니다.
+ application.yml 에 "spring.ai.openai.api-key"에 대한 내용을 추가해야 합니다. 해당 라이브러리에서 빈 등록하면서 토큰을 바로 사용하는 구조인 것 같더라고요!
=> feat: Gpt4o LLM Service 구현체를 제작하였습니다.

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/ArtworkController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/domain/Artwork.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/domain/ArtworkRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/dto/request/ArtworkSaveRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/dto/request/ArtworkUpdateRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/dto/response/ArtworkSavedResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/dto/response/ArtworkSavedResponses.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/exception/ArtworkExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/exception/ArtworkNoSuchElementException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/artwork/service/ArtworkService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/artwork/domain/ArtworkRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/artwork/service/ArtworkServiceTest.java
---
* 구현 내용
- 캐릭터 작품 ArcWork 클래스 패키지 구성 및 구현 (CRUD)
- 테스트 코드 구현 (Repository, Service)
=> [feat] 캐릭터 작품 ArtWork 클래스 패키지 구성 및 구현

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/apply/service/VisionApplyManageService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/apply/service/VisionApplyService.java
---
* 구현 내용
* Vision 관련 클래스에 Character ModelType → CharacterVisionType 변경 안된 필드 변경
=> fix: Vision 관련 클래스에 Character ModelType → CharacterVisionType 변경 안된 필드 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/converter/ByteArrayToBufferedImageConverter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/converter/ByteArrayToPngBufferedImageConverter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/converter/OneBufferedImageToFourSubImagesConverter.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/converter/OneBufferedImageToFourSubImagesConverterTest.java
---
* 구현 내용
byte[] to BufferImage에 대한 컨버터와
한 장의 이미지를 4장으로 나누어주는 컨버터를 제작하였습니다.
=> [feat] 이미지 관련된 컨버터 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/Hashtag.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagTest.java
=> test: Hashtag test 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/converter/LongListToStringConverter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/converter/UrlListToStringConverter.java
---
* 구현 내용
컨버터 빈 등록 Service → Component로 변경
=> 컨버터 빈 등록 Service → Component로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/AuthConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationExceptionHandler.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/jwt/JwtExtractor.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
---
- 인증 인터셉터 → 필터로 리팩토링
- 필터 예외 추가
=> refactor & feat: 인증 인터셉터 → 필터로 리팩토링 & 필터 예외 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponse.java
=> fix: dto 스펠링 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/Character.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/PaymentType.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/AddCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/service/CharacterServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java
---
* 구현 내용
* Chacter 클래스 payment 필드 추가 및 테스트 코드 변경
=> refactor: Character 클래스 payment 필드 추가 및 테스트 코드 변경

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/FourtoonCookieApplication.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/s3/service/DiaryImageS3Service.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/sqs/service/StableDiffusionSQSApplyService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/sqs/service/StableDiffusionSQSReplyService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/ObjectMapperConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/SQSConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/vision/reply/service/VisionReplyService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/aws/sqs/service/StableDiffusionSQSApplyServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/aws/sqs/service/StableDiffusionSQSReplyServiceTest.java
---
추후 구현될 StableDiffusionVisionApplyService에서 활용할 SQS 관련 로직을 구성하였습니다
* 구현 내용
1. SQSConfig를 추가하였습니다. 
(관련 커밋: d8f1b2704100a6f549244ee1ff6e94607794cbf3 )
2. aws 패키지 구조를 재정립하였습니다. 
(관련 커밋: 49ecb31cfa7436f8535838cffe87eb550e79f531 )
3. StableDiffusion에 대한 SQS 서비스 로직을 구현하였습니다.
4. 어플리케이션에 스케줄링을 허용시켰습니다. 
(관련 커밋: 7b9380f80fe010b638a63462ce27d7b49044d068 )
=> [feat] StableDiffusion과의 SQS 통신 로직 구현 

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/response/CharacterResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/service/CharacterServiceTest.java
=> refactor: 캐릭터 관련 클래스 리팩토링

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/artwork/domain/ArtworkRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java
=> fix: Diary 통합 충돌 해결

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/llm/service/OpenAILLMService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/llm/service/OpenAIGpt4oLLMServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/vision/apply/service/DallE3VisionApplyServiceTest.java
=> fix: AI 충돌 해결

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java
---
* 구현 내용
메서드 제거 -    public void updateDiary(Long diaryId, DiaryPaintingImagesUpdateRequest request) {
=> fix: 필요 없는 메서드 및 테스트 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/HealthController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java
---
* 구현 내용
* feat: HealthController
=> feat: HealthController

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/HealthController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java
* feat: HealthController
* refactor: health 상태코드 200 반환
---
* 구현 내용
=> merge: HealthController (#49)

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/HealthController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java
* feat: HealthController
* refactor: health 상태코드 200 반환
+ 기존의 merge와 같은 경우에는 squash merge되어서 revert후 새로 다시 진행합니다.
=> feat: HealthController (#49)

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java
---
* 구현 내용
- MemberNotFoundException → 404 상태코드 반환
- JWT 에러(AuthenticationException 인 경우) → 401 상태코드 반환
```java
} catch (SignatureException e) {
throw new AuthenticationException("Invalid JWT signature", e);
} catch (ExpiredJwtException e) {
throw new AuthenticationException("Expired JWT token", e);
} catch (UnsupportedJwtException e) {
throw new AuthenticationException("Unsupported JWT token", e);
} catch (MalformedJwtException e) {
throw new AuthenticationException("Malformed JWT token", e);
} catch (IllegalArgumentException e) {
throw new AuthenticationException("JWT token compact of handler are invalid", e);
```
=> [feat] MemberNotFoundException, AuthenticationException 에러 핸들링 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/dto/response/MemberSavedResponse.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
---
* 구현 내용
- Member `email` 필드 제거
=> [refactor] Member 클래스 email 필드 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
---
* 구현 내용
Member 클래스 변경 deletedAt 필드 명 deletdDateTime 으로 변경
=> [refactor] Member 클래스 변경 deletedAt 필드 명 deletdDateTime 으로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java
---
Member 클래스 baseEntity 상속 추가
=> [feat] Member 클래스 baseEntity 상속 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/MemberController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/dto/request/MemberSaveRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
---
* 구현 내용
[refactor] patchMember 메소드를 postMember 메소드로 변경
=> [refactor] patchMember 메소드를 postMember 메소드로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/MemberController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/dto/request/MemberSaveRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/dto/response/MemberSavedResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
=> [merge] develop에서 main으로 병합

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java
---
* 구현 내용
- 백엔드 memberId를 supabase sub값이 아닌 random.UUID로 생성 했던 버그 수정
- 회원가입 안되는 버그 수정
=> [fix] member 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java
---
* 구현 내용
멤버 회원가입 하는데, 멤버 아이디가 디비에 저장되지 않아 필터를 통과하지 못해 회원가입을 못하는 버그 수정
아이디 중복 회원가입 방지 기능 추가 해야함
=> [fix] 멤버 회원가입 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberDuplicateException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
---
중복 회원가입 방지 기능 추가
MemberDuplicateException가 필터까지 전송되어 GlobalExceptionControllerAdvice에서 RuntimeException으로 예외 변환하는 문제 생김
=> [feat] 중복 회원가입 방지 기능 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/exception/GlobalExceptionControllerAdvice.java
---
* 구현 내용
MemberDuplicateException가 필터까지 전송되어 GlobalExceptionControllerAdvice에서 RuntimeException으로 예외 변환하는 문제 생김
=> [fix] 글로벌 어드바이스가 예외 변환하는 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilter.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/exception/GlobalExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberDuplicateException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
=> [merge] 2차 배포

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/Character.java
---
* 구현 내용
character 테이블명 Mysql 예약어와 겹쳐 백틱추가
=> [fix] character 테이블명 Mysql 예약어와 겹쳐 백틱추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/Character.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepositoryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java
=> [merge] 2차 머지

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/dto/request/DiaryPaintingImagesUpdateRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java
---
* 구현 내용
다이어리 paintingImageUrls 기본 이미지 제거
=> [feat] 다이어리 paintingImageUrls 기본 이미지 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/dto/request/DiaryFavoriteRequest.java
=> fix: 즐겨찾기 요청 isFavorite 객체로 변경

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/LambdaInvoker.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryLambdaInvocationException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
---
* 구현 내용
- LambdaConfig 클래스 생성
- LambdaInvoker 클래스 생성
- 람다로 일기 이미지 생성 요청 기능 추가
- 요청 후 응답 받지않음
- 람다 호출 실패 시 일기 저장 X
=> [feat] AWS Lambda에 일기 이미지 생성 요청 기능 추가

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/LambdaInvoker.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/dto/request/DiaryFavoriteRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/dto/request/DiaryPaintingImagesUpdateRequest.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryExceptionControllerAdvice.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryLambdaInvocationException.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/domain/DiaryTest.java
=> [merge] 일기 이미지 생성 람다 코드 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/S3Config.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/SQSConfig.java
=> [fix] credentialsProvider(ProfileCredentialsProvider.create()) 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/S3Config.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/SQSConfig.java
=> [merge] credentialsProvider(ProfileCredentialsProvider.create()) 제거 후 머지

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
---
* 구현 내용
AWS Lambda에 일기 이미지 수정 요청 기능 추가
favorite 에서 diaryRepository.save(foundDiary); 제거 - 더티체킹
=> [feat] AWS Lambda에 일기 이미지 수정 요청 기능 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/MemberController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
---
* 구현 내용
fix: 멤버 소프트삭제 하드삭제로 변경
feat: 멤버 하드삭제시, 멤버가 쓴 일기 전부 제거
=> fix & feat: 멤버 소프트삭제 하드삭제로 변경, 멤버 하드 삭제시 멤버가 쓴 일기 전부 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/DiaryRepository.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/MemberController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
=> [merge] fix 후 머지

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/S3Config.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/SQSConfig.java
=> [refactor] 사용하지 않는 라이브러리 제거

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
=> [hotfix] 이미지 그리드 포지션 0~3 으로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
[merge] 이미지 그리드 포지션 변경 후 머지
---
* 구현 내용
=> [merge] 이미지 그리드 포지션 변경, 이미지 수정 시 이미지 생성 람다 요청 비동기 호출로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/diaryImageGenerationPayload/DiaryImageGenerationCharacterPayload.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/diaryImageGenerationPayload/DiaryImageGenerationCharacterResponse.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/diaryImageGenerationPayload/DiaryImageGenerationLambdaPayload.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
#objectMapper.writeValueAsString(payload)
---
* 구현 내용
"," son 데이터에 `,`가 섞이는 등의 경우 제대로 json 데이터로 만들어지지 않던 것을 ObjectMapper로 수정
=> [bug] 일기 이미지 생성 람다호출 json 생성, ObjectMapper로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/FourtoonCookieApplication.java
=> hotfix: @EnableAsync

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/FourtoonCookieApplication.java
=> [merge] @EnableAsyn 추가 후 merge

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/LambdaInvoker.java
=> hotfix: 람다 에러 발생 부분 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/LambdaInvoker.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/event/DiaryLambdaCallEventListener.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/event/domain/DiaryLambdaCallEvent.java
=> merge: 람다 비동기 요청을 EventListener로 변경 후 머지

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/event/DiaryLambdaCallEventListener.java
=> hotfix: async 트랜잭션

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/event/DiaryLambdaCallEventListener.java
=> hotfix: async 트랜잭션 (#109)

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java
=> hotfix: 람다 에러시 재시도 횟수 0번으로 변경

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java
=> [merge] 람다 에러시 재시도 횟수 0번으로 변경 후 머지

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java
fix: 람다 요청 및 읽기 시간 변경
---
* 구현 내용
=> fix: 람다 요청 및 읽기 시간 변경

fourtooncookie/build.gradle, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java
=> [merge] dev -> main

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/config/LambdaConfig.java
=> refactor: 람다 클라이언트 소켓 타임아웃 3분으로 조정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/diaryImageGenerationPayload/DiaryImageGenerationLambdaInvoker.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
=> [fix] @Async 내부클래스에서 안되는 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/lambda/diaryImageGenerationPayload/DiaryImageGenerationLambdaInvoker.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
=> [merge] @Async 내부클래스에서 안되는 버그 수정 후 merge

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/aws/s3/service/DiaryImageS3ServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/config/authentication/AuthenticationFilterTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/authorization/DiaryOwnerAuthorizationInterceptorTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/exception/DiaryExceptionTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiaryServiceTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/jwt/JwtExtractorTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/MemberTest.java, fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
=> [feat] 테스트 코드 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/domain/Member.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
---
* 구현 내용
- [GET] /diaries/{diaryId}  추가
- 사용 안했던 멤버 소프트 딜리트 코드 제거
=> [feat] 멤버 소프트 딜리트 코드 삭제, 일기 단일 조회 기능 추가

fourtooncookie/build.gradle
---
* 구현 내용
로그수집을 위한 sentry 설정입니다.
build.gradle을 통해 필요한 설정 및 의존성을 추가합니다.
application.properties를 통해 sentry 설정을 합니다.
=> [build] sentry 설정

.github/workflows/pr-develop-test.yml
---
* 구현 내용
-  pr-develop-test.yml SQS 관련 환경변수 추가
=> [CI/CD] pr-develop-test.yml SQS 테스트 관련 환경변수 추가

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryLambdaService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
---
* 구현 내용
- DiaryPaintingImageGenerationStatus가 하나라도 `FAILURE` 라면 DiaryStatus가 `FAILED`가 되도록 변경
- Diary클래스 updateDiaryStatus()가 외부에 의존하는게 아닌 Diary 자체에 의존하도록 변경
=> [fix] DiaryStatus 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryLambdaService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
=> [merge] DiaryStatus 버그 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
---
* 구현 내용
DiaryService에서 Member의 UUID만 필요하기 때문에, 이를 컨트롤러에서 가져오기 때문에 필요없는 MemberService 의존성 주입 제거
=> [refactor] 멤버 서비스 의존관계 코드 리팩토링

.github/workflows/pr-develop-test.yml
=> [build] pr-develop-test

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/listener/DiarySQSMessageListener.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/domain/NotificationToken.java
=> [fix] merge 시 생긴 문제 해결

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/web/exception/GlobalExceptionControllerAdvice.java
---
* 구현 내용
- Exception 처리 시 올바른 ResponseStatus 코드 반환 수정
- verifyUniqueDiary() 충돌 해결
=> [fix] Exception 처리 시 올바른 ResponseStatus 코드 반환 수정, verifyUniqueDiary() 충돌 해결

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/translation/TranslationService.java
---
* 구현 내용
- @Id 필드가 private일 수 있기에 접근을 허용한 이후 진행해야 하는 데, 해당 로직이 없어서 버그가 생기던 문제를 해결했습니다.
=> [bug] TranslationService의 getClassId private 필드 접근 관련 오류 해결

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/NotificationController.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/NotificationService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/domain/NotificationToken.java, fourtooncookie/src/main/resources/messages/messages_en.xml, fourtooncookie/src/main/resources/messages/messages_ko.xml
---
* 구현 내용
알림이 토큰에 따라 언어별로 전송됩니다.
=> [feat] 알림을 토큰에 따라 언어별로 전송되도록 구현

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/NotificationService.java
=> [bug] notification . 붙이기

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/NotificationService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/domain/NotificationToken.java
---
* 구현 내용
동일한 토큰 존재 시 locale도 동시에 수정하도록 수정
=> [fix] 동일한 토큰 존재 시 locale도 동시에 수정하도록 수정

fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/NotificationService.java, fourtooncookie/src/main/java/com/startingblue/fourtooncookie/notification/service/NotificationMessageSourceService.java
=> [hotfix] notification 보낼때 localContextHolder 값은 비어 있던 버그 수정
